### ISSUE TITLE
Fedora 40 - COPR causing DE to crash 

### ISSUE THREAD

**Issue by BrycensRanch** [vulongm/copr-gamescope-git#2]
# Gamescope triggering complete freeze of Plasma 6 DE.
_Note: Audio from other applications such as Google Chrome still continues playing, the game itself never seems to get to a state where it's able to even THINK about playing audio, lol_ 

As the title says, my entire desktop environment crashes when I actually try the COPR at the moment. Also, maybe it's the more up to date wlroots? Fedora 40 provides a sufficient wlroots btw. When I use the same semver version gamescope package from Fedora's repos. 

## System Info: 
```
Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.9.0-0.rc2.20240406gt104db052.327.vanilla.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Acer
Product Name: Predator PH315-54
System Version: V1.15
```

## Fastfetch output
```
romvnly@Shadow-PH315-54
-----------------------
OS: Fedora Linux 40 (KDE Plasma) x86_64
Host: Predator PH315-54 V1.15
Kernel: 6.9.0-0.rc2.20240406gt104db052.327.vanilla.fc40.x86_64
Uptime: 1 hour
Battery: 79%% [AC Connected]

Packages: 3910 (rpm), 33 (flatpak), 7 (brew)
Shell: bash 5.2.26
Display: 1920x1080 @ 165Hz
Display: 1920x1080 @ 75Hz [External]
Display: 1920x1080 @ 144Hz [Built-in]
Terminal: kitty 0.33.1

CPU: 11th Gen Intel(R) Core(TM) i7-11800H (16) @ 4.60 GHz
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q
GPU: Intel UHD Graphics
Memory: 9.42 GiB / 15.39 GiB (61%)
````

Packages I used to compare
```
❯ sudo dnf list --installed | grep wlroots
[sudo] password for romvnly: 
wlroots.x86_64                                                                  0.17.2-1.fc40                                           @fedora                                                                

~ took 3s 
❯ sudo dnf list --installed | grep gamescope
gamescope.x86_64                                                                3.14.2-1.fc40                                           @fedora                                                                
```

**Comment by vulongm** [comment]
Thanks for the report, I wonder what is a good way to approach this. In the git branch they did update the required version to be 0.18, the current stable build can still use the 0.17 version in Fedora's repo. https://github.com/ValveSoftware/gamescope/commit/ef90e1f933afa32aca54fa0332779fb40375aa0a

**Comment by vulongm** [comment]
@BrycensRanch I changed it so the newer wlroots is only used as part of the build process for gamescope. Let me know if that works there.

**Comment by BrycensRanch** [comment]
Alright, I'll give it a try today. Thanks!

**Comment by BrycensRanch** [comment]
This seems to have fixed the issue, besides gamescope generally sucking with NVIDIA GPUs, lol. Thanks!

**Comment by vulongm** [comment]
@BrycensRanch If you still use the package I re-added the separate wlroots into the repo. Is the issue still occurring with it re-added?
