### ISSUE TITLE
Wrong instructions on COPR

### ISSUE THREAD

**Issue by Tiagoquix** [vulongm/copr-gamescope-git#6]
Hi there.

On the page https://copr.fedorainfracloud.org/coprs/vulongm/gamescope-git/, the Fedora Atomic instructions point to game**mode**-git instead of game**scope**-git.

It also may be interesting to add similar instructions for the actual game**mode**-git: https://copr.fedorainfracloud.org/coprs/vulongm/gamemode-git/

Thank you for mantaining these COPRs.

**Comment by vulongm** [comment]
Thanks for the notice, I went ahead and updated the instructions for both repos.
